routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/run_migrate', function(){
    $exitCode = Artisan::call('migrate');
    dd($exitCode);
});
Route::get('/rollback', function(){
    $exitCode = Artisan::call('migrate:rollback');
    dd($exitCode);
});

Route::get('/test', function(){
    dd(App\Message::with('children')->get());
});
Route::get('/', function () {
    return redirect('products');
//    return view('welcome');
})->name('welcome');
Route::get('routes', function(){
    $routes = Route::getRoutes();
    foreach ( $routes as $route ) {
        dump($route);
    }
    die();
//    return dd(Route::getRoutes());
})->name('routes');

Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('loginGoogle');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider')->name('loginFacebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleFacebookProviderCallback');

Auth::routes();
//Route::get('/users', 'UserController@index')->name('user-edit')->midleware();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('products/{id}/set_thumbnail/', 'ProductController@setThumbnail')->name('products.setThumbnail');
Route::post('products/{id}/add_images/', 'ProductController@addImage')->name('products.addImage');
Route::resource('products', 'ProductController');

Route::get('cart/getControllerUrls', 'CartController@getControllerUrls')->name('cart.getControllerUrls');
Route::post('cart/{id}/addCart/', 'CartController@addCart')->name('cart.addCart');
Route::get('cart/getCartItems/', 'CartController@getCartItems')->name('cart.getCartItems');
Route::get('cart/getCartItemsJson/', 'CartController@getCartItemsJson')->name('cart.getCartItemsJson');
Route::delete('cart/{id}/deleteCartItem/', 'CartController@deleteCartItem')->name('cart.deleteCartItem');
Route::put('cart/{id}/changeCartItemCount/', 'CartController@changeCartItemCount')->name('cart.changeCartItemCount');

Route::resource('images', 'ImageController');

Route::resource('checkout', 'CheckoutOrdersController');

Route::get('orders/getAllOrdersJson', 'OrdersController@getAllOrdersJson');
Route::resource('orders', 'OrdersController');

Route::get('messages/childrens', 'MessageController@getChildrenMessages');
Route::resource('messages', 'MessageController');

/*
 * Admin Routes
 */
Route::middleware(['auth', 'checkrole'])->prefix('admin')->group(function(){
    Route::get('/', function(){
        return view('admin.dashboard');
    });

    Route::post('products/getProducts', 'Admin\AdminProductController@getProducts');
    Route::post('products/getProduct', 'Admin\AdminProductController@getProduct');
    Route::post('products/saveCategories', 'Admin\AdminProductController@saveCategories');
    Route::resource('products', 'Admin\AdminProductController', ['as'=>'admin']);

    Route::post('categories/validateUniqueCategoryByTitle', 'Admin\AdminCategoryController@validateUniqueCategoryByTitle');
    Route::post('categories/getCategories', 'Admin\AdminCategoryController@getCategories');
    Route::resource('categories', 'Admin\AdminCategoryController');


});

resources/views/headers/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="googlebot" content="noindex,nofollow">
<meta name="yandex" content="noindex,nofollow">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="base-url" content="{{ URL::to('/') }}">

<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">

resources/views/headers/top-main-menu.blade.php
<nav id="siteHeader" class="navbar navbar-expand-md navbar-light bg-white shadow-sm site-top-menu">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('products.index') }}">{{ __('Магазин') }}</a>
                </li>

                <!-- Authentication Links -->
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Регистрация') }}</a>
                    </li>
                @endif

                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Войти') }}</a>
                    </li>
                @endif

                @auth()
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('home') }}">{{ __('Пользователи') }}</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('products.create') }}">{{ __('Создать товар') }}</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('orders.index') }}">{{ __('Заказы') }}</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle header_user" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}<span class="header_user-role">({{ Auth::user()->role }})</span> <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Выйти') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endauth

                <li class="nav-item">
                    <header-cart-button></header-cart-button>
                </li>
            </ul>
        </div>
    </div>
</nav>