routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/run_migrate', function(){
    $exitCode = Artisan::call('migrate');
    dd($exitCode);
});
Route::get('/rollback', function(){
    $exitCode = Artisan::call('migrate:rollback');
    dd($exitCode);
});

Route::get('/test', function(){
    dd(App\Message::with('children')->get());
});
Route::get('/', function () {
    return redirect('products');
//    return view('welcome');
})->name('welcome');
Route::get('routes', function(){
    $routes = Route::getRoutes();
    foreach ( $routes as $route ) {
        dump($route);
    }
    die();
//    return dd(Route::getRoutes());
})->name('routes');

Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('loginGoogle');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider')->name('loginFacebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleFacebookProviderCallback');

Auth::routes();
//Route::get('/users', 'UserController@index')->name('user-edit')->midleware();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('products/{id}/set_thumbnail/', 'ProductController@setThumbnail')->name('products.setThumbnail');
Route::post('products/{id}/add_images/', 'ProductController@addImage')->name('products.addImage');
Route::resource('products', 'ProductController');

Route::get('cart/getControllerUrls', 'CartController@getControllerUrls')->name('cart.getControllerUrls');
Route::post('cart/{id}/addCart/', 'CartController@addCart')->name('cart.addCart');
Route::get('cart/getCartItems/', 'CartController@getCartItems')->name('cart.getCartItems');
Route::get('cart/getCartItemsJson/', 'CartController@getCartItemsJson')->name('cart.getCartItemsJson');
Route::delete('cart/{id}/deleteCartItem/', 'CartController@deleteCartItem')->name('cart.deleteCartItem');
Route::put('cart/{id}/changeCartItemCount/', 'CartController@changeCartItemCount')->name('cart.changeCartItemCount');

Route::resource('images', 'ImageController');

Route::resource('checkout', 'CheckoutOrdersController');

Route::get('orders/getAllOrdersJson', 'OrdersController@getAllOrdersJson');
Route::resource('orders', 'OrdersController');

Route::get('messages/childrens', 'MessageController@getChildrenMessages');
Route::resource('messages', 'MessageController');

/*
 * Admin Routes
 */
Route::middleware(['auth', 'checkrole'])->prefix('admin')->group(function(){
    Route::get('/', function(){
        return view('admin.dashboard');
    });

    Route::post('products/getProducts', 'Admin\AdminProductController@getProducts');
    Route::post('products/getProduct', 'Admin\AdminProductController@getProduct');
    Route::post('products/saveCategories', 'Admin\AdminProductController@saveCategories');
    Route::resource('products', 'Admin\AdminProductController', ['as'=>'admin']);

    Route::post('categories/validateUniqueCategoryByTitle', 'Admin\AdminCategoryController@validateUniqueCategoryByTitle');
    Route::post('categories/getCategories', 'Admin\AdminCategoryController@getCategories');
    Route::resource('categories', 'Admin\AdminCategoryController');


});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    public $fillable = ['id', 'title', 'description', 'price', 'user_id'];

//    public function getHelloAttribute(){
//        return $this->title . ' - ' . $this->price;
//    }
//    public function getThumnailUrl(){
//        $thumbnail = $this->thumbnail();
//        return Storage::url($thumbnail->path);
//    }

    public function thumbnail()
    {
        return $this->hasOne('App\Image', 'id', 'thumbnail_id');
    }

    public function images()
    {
        return $this->hasMany('App\Image')->orderBy('id', 'desc');
    }

    public function orderItems()
    {
        return $this->hasMany('App\OrderItem');
    }

    public function messages() {
        return $this->hasMany('App\Message');
    }

    public function categories() {
        return $this->belongsToMany('App\Category', 'category_product');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request as Request;
use App\Image as Image;
use App\Product as Product;
use Illuminate\Support\Facades\Auth as Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Routing\UrlGenerator;
use Illuminate\Support\Collection;
use App\Http\Middleware\CheckRole;
use Illuminate\Support\Arr;


class ProductController extends Controller
{
    public function __construct(Request $request) {
//        if(
//            $request->route()->named('products.setThumbnail')
//            || $request->route()->named('products.addImage')
//            || $request->route()->named('products.destroy')
//            || $request->route()->named('products.update')
//            || $request->route()->named('products.edit')
//            || $request->route()->named('products.store')
//            || $request->route()->named('products.create')
//        ) {
//            $this->middleware(['auth']);
//        }

    }


    /**
     *
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'desc')
            ->with('thumbnail')
            ->paginate(8);
        return view('products.index-product', ['products' => $products ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create-product');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'min:3'],
            'price' => ['required'],
        ]);
        $product = new Product([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'price' => $request->input('price'),
            'user_id' => Auth::id(),
        ]);
        $product->save();

        if ($request->hasFile('image')) {
            $image = $product->thumbnail()->create([
                'filename' => $request->image->hashName(),
                'path' => $request->image->store('public/products'),
                'product_id' => $product->id
            ]);
            $product->thumbnail_id = $image->id;
            $product->save();
        }
        return redirect()->route('products.edit', $product->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::with(['thumbnail', 'images'])->find($id);
        $thumbnail_obj = $product->thumbnail;
        $thumbnail_url = $thumbnail_obj ? $thumbnail_obj->path : Storage::url('products/default.png');
        $data = [
            'product' => $product,
            'thumbnail' => $thumbnail_url,
            'gallery' => $product->images,
        ];
        return view('products.edit-product', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
//        $product = Product::find($id)->with(['thumbnail', 'images']);
        $product = Product::with(['thumbnail', 'images'])->find($id);
        $thumbnail_obj = $product->thumbnail;
        $thumbnail_url = $thumbnail_obj ? $thumbnail_obj->path : Storage::url('products/default.png');
        $data = [
            'product' => $product,
            'thumbnail' => $thumbnail_url,
            'gallery' => $product->images,
        ];
        return view('products.edit-product', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $request->validate([
            'title' => ['required'],
            'price' => ['required', 'numeric']
        ]);

        $product->title = $request->input('title');
        $product->description = $request->input('description');
        $product->price = $request->input('price');
        $product->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        return $id;
        Product::find($id)->delete();
        return route('products.index');
    }

    public function addImage(Request $request, $id) {
        $request->validate([
           'image' => 'image'
        ]);
        $image_name = $request->image->hashName();
        $image_path = $request->file('image')->store('public/products');

        $product = Product::find($id);

        $image = $product->images()->create([
            'filename' => $image_name,
            'path' => $image_path
        ]);

        $html = '<div class="product-gallery_item" data-image-id="'.$image->id.'">';
        $html .= '<div class="product-gallery_item-actions">';
        $html .= '<div class="product-gallery_item-action product-gallery_item-action__thumbnail"><i class="far fa-check-circle"></i></div>';
        $html .= '<div class="product-gallery_item-action product-gallery_item-action__delete"  data-delete-image="'.route('images.destroy', $image->id).'">';
        $html .= '<i class="far fa-trash-alt"></i>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<img src="'.$image->path.'"  alt="'.$image->product->title.'" title="'.$image->product->title.'" class="product-gallery_item-image">';
        $html .= '</div>';

        return $html;
    }

    public function setThumbnail(Request $request, $id){
        $thumbnail_id = $request->input('image_id');
        $product = Product::find($id);
        $product->thumbnail_id = $thumbnail_id;
        $product->save();
        return 'true';
    }


}

resources/views/products/create-product.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data" class="col-lg-12">
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="productTitle">
                        Заголовок
                        @error('title')
                            <span class="label__error">{{ $message }}</span>
                        @enderror
                    </label>
                    <input id="productTitle" name="title" value="{{ old('title') }}" type="text" class="form-control @error('title') input__error @enderror" placeholder="Enter Title">
                </div>
                <div class="form-group col-lg-6">
                    <label for="productPrice">
                        Цена
                        @error('price')
                            <span class="label__error">{{ $message }}</span>
                        @enderror
                    </label>
                    <input id="productPrice" name="price" value="{{ old('price') }}" type="number" step="0.01" class="form-control @error('price') input__error @enderror" placeholder="Enter Price">
                </div>
                <div class="form-group col-lg-12">
                    <label for="productDiscription">Описание</label>
                    <textarea id="productDiscription" name="description" value="{{ old('description') }}" class="form-control" placeholder="Enter Description"></textarea>
                </div>

                <div class="form-group col-lg-6">
                    <label for="productImage">Изображение: </label>
                    <input id="productImage" name="image" value="{{ old('image') }}" type="file">
                </div>
                <div class="form-group col-lg-6 text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
            @csrf
        </form>
    </div>
</div>
@endsection

resources/views/products/edit-product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container product-detail">
        @auth() @if(Auth::user()->role == 'admin')
            <div class="product-detail_actions">
                <div class="product-detail_action product-detail_action-edit"><i class="fas fa-pencil-alt"></i></div>
                <div class="product-detail_action product-detail_action-save product-detail_action__hidden"><i class="far fa-save"></i></div>
            </div>
        @endif @endauth
        <div class="row">
            <div class="col-4">
                <div class="product-detail_thumbnail" data-default-thumbnail="{{ getDefaultProductThumbnail() }}">
                    <img src="{{$thumbnail}}" class="img-fluid" alt="{{$product->title}}" title="{{$product->title}}">
                </div>
            </div>
            <div class="col-8">
                <div class="product-detail_content" data-update-url="{{ route('products.update', $product->id) }}">
                    <h1 class="product-detail_content-title">{{ $product->title }}</h1>
                    <div class="product-detail_content-description">
                        <div class="product-detail_content-description-text">{!! $product->description !!}</div>
                    </div>
                    <span class="product-detail_content-price global-currency-price" data-currency="грн.">{{ $product->price }}</span>
                </div>
                <div class="product-detail_buttons">
                    <div class="button button__gray product-detail_button-buy" data-add-cart-url="{{ route('cart.addCart', $product->id) }}" @click="buyProduct">Купить</div>
                    @auth() @if(Auth::user()->role == 'admin')
                        <div class="button button__gray product-detail_button-remove" data-destroy-product-url="{{ route('products.destroy', $product->id) }}">Удалить</div>
                    @endif @endauth
                </div>
            </div>
        </div>
        <div class="owl-carousel product-gallery mt-4" data-setthumbnail-url="{{ route('products.setThumbnail', $product->id) }}">
            @auth() @if(Auth::user()->role == 'admin')
                <div id="addNewImage" class="product-gallery_item product-gallery_item__add">+</div>
            @endif @endauth
            @if( count( $gallery ) )
                @foreach( $gallery as $image )
                    <div class="product-gallery_item" data-image-id="{{ $image->id }}">
                        @auth() @if(Auth::user()->role == 'admin')
                            <div class="product-gallery_item-actions">
                                <div class="product-gallery_item-action product-gallery_item-action__thumbnail"><i class="far fa-check-circle"></i></div>
                                <div class="product-gallery_item-action product-gallery_item-action__delete"  data-delete-image="{{ route('images.destroy', $image->id) }}">
                                    <i class="far fa-trash-alt"></i>
                                </div>
                            </div>
                        @endif @endauth
                        <img src="{{ $image->path }}"  alt="{{$product->title}}" title="{{$product->title}}" class="product-gallery_item-image">
                    </div>
                @endforeach
            @endif
        </div>
    </div>
    @auth() @if(Auth::user()->role == 'admin')
        <form action="{{ route('products.addImage', $product->id) }}" class="product-add-image-form">
            <input type="file" name="image" id="addImageField"/>
        </form>
    @endif @endauth
    <div class="container">
        @auth()
            <tim-write-message :product="{!! $product->id !!}"></tim-write-message>
        @endauth
        <tim-messages :product="{!! $product->id !!}"></tim-messages>
    </div>
@endsection

resources/views/products/index-product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row products-list">
            @foreach($products as $product)
                @auth() @if( Auth::user()->role == 'Admin' )
                    <a href="{{route('products.edit', $product->id)}}" class="col-6 col-md-3 products-list-item">
                @else
                    <a href="{{route('products.show', $product->id)}}" class="col-6 col-md-3 products-list-item">
                @endif @endauth
                @guest()
                    <a href="{{route('products.show', $product->id)}}" class="col-6 col-md-3 products-list-item">
                @endguest
                    <?php
                        $product_image = '';
                        $product_thumbnail = $product->thumbnail;
                        if( $product_thumbnail ) {
                            $product_image = $product_thumbnail->path;
                        } else {
                            $product_image = 'products/default.png';
                        }
                    ?>
                    <div class="products-list-item_image"><img class="img-fluid" src="{{ $product_image }}" alt=""></div>
                    <div class="products-list-item_price global-currency-price" data-currency="грн.">{{$product->price}}</div>
                    <div class="products-list-item_title"><h4>{{$product->title}}</h4></div>
                </a>
            @endforeach
        </div>
        <div class="row">
            <div class="col-12">
                {{ $products->links() }}
            </div>
        </div>
    </div>
@endsection